name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Triggers the workflow on push events to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specifies the Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages  # Target branch to deploy to
        keep_files: false  # Set to true to retain files not present in the new deployment
