name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Triggers the workflow on push events to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.6
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specifies the Node.js version
        cache: 'pnpm'  # Optionally caches the dependencies using GitHub's cache action

      
    - name: Install Dependencies
      run: pnpm install  # Installs dependencies using pnpm
    
    - name: Build Project
      run: pnpm run build  # Builds the project using pnpm
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages  # Target branch to deploy to
        keep_files: false  # Set to true to retain files not present in the new deployment
    
